name: Google Chat Notification
on:
  pull_request:
    types: [opened]

jobs:
  notify:
    name: Chat Notification
    runs-on: ubuntu-latest
    steps:
      - name: google-chat-notification
        uses: Co-qn/google-chat-notification@v1
        with:
          name: Pull Request Opend
          url: ${{ secrets.GCHAT_WEBHOOK_URL }}
          status: ${{ job.status }}
